# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2302b301dbfce4e8478eab22d58d9b7ca7b558669f41917aa5f88465ecabe22c38f8ef90337bb70a742ee51ba53e8d7256136e082999aff73b972429d68e608e

test:
  secret_key_base: 7dcf8dfa058b53c14e1c72f0ee877d576f072702a73d4b2d1bb5ad3069deb19b875b6106f2e6c7b133b1518a2aae4a781464622cf56a392c4f0a607396d33b19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
